In [38]:
import pandas as pd
import numpy as np

In [39]:
data = {
  'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog',
  'dog'],
  'name': ['Daisy', 'Bella', 'Noodle', 'Charlie', 'Max', 'Molly', 'Draco', 'Kenzo',
  'Milo', 'Cooper'],
  'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
  'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
  'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']
}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

### Zadanie 1

In [40]:
animals = pd.DataFrame(data, index=labels)

In [41]:
animals

  animal     name  age  visits priority
a    cat    Daisy  2.5       1      yes
b    cat    Bella  3.0       3      yes
c  snake   Noodle  0.5       2       no
d    dog  Charlie  NaN       3      yes
e    dog      Max  5.0       2       no
f    cat    Molly  2.0       3       no
g  snake    Draco  4.5       1       no
h    cat    Kenzo  NaN       1      yes
i    dog     Milo  7.0       2       no
j    dog   Cooper  3.0       1       no

### Zadanie 2

In [42]:
# Display first 3 rows
animals.head(3)

  animal    name  age  visits priority
a    cat   Daisy  2.5       1      yes
b    cat   Bella  3.0       3      yes
c  snake  Noodle  0.5       2       no

In [43]:
# Dispay animal and age columns
animals[["animal", "age"]]

  animal  age
a    cat  2.5
b    cat  3.0
c  snake  0.5
d    dog  NaN
e    dog  5.0
f    cat  2.0
g  snake  4.5
h    cat  NaN
i    dog  7.0
j    dog  3.0

In [44]:
# Data from indexes 3,4,8 from columns 'visits' and 'priority'
animals.iloc[[3, 4, 8]][['visits', 'priority']]

   visits priority
d       3      yes
e       2       no
i       2       no

In [45]:
# Rows where visits count is greater than 2
animals.loc[animals["visits"] > 2].dropna()

  animal   name  age  visits priority
b    cat  Bella  3.0       3      yes
f    cat  Molly  2.0       3       no

In [46]:
# Rows where animals is a cat and and it's age is below 4 y.o
animals.loc[(animals["animal"] == "cat") & (animals["age"] < 4)]

  animal   name  age  visits priority
a    cat  Daisy  2.5       1      yes
b    cat  Bella  3.0       3      yes
f    cat  Molly  2.0       3       no

In [47]:
# Rows where animal age is is range 2-4 (including) y.o
age_range = animals["age"].between(2, 4, inclusive="both")
animals[age_range]

  animal    name  age  visits priority
a    cat   Daisy  2.5       1      yes
b    cat   Bella  3.0       3      yes
f    cat   Molly  2.0       3       no
j    dog  Cooper  3.0       1       no

### Zadanie 3

In [48]:
# Add new record to animals dataFrame
k = ["dog", "Buddy", 5.5, 2, False]
animals.loc["k"] = k
animals

  animal     name  age  visits priority
a    cat    Daisy  2.5       1      yes
b    cat    Bella  3.0       3      yes
c  snake   Noodle  0.5       2       no
d    dog  Charlie  NaN       3      yes
e    dog      Max  5.0       2       no
f    cat    Molly  2.0       3       no
g  snake    Draco  4.5       1       no
h    cat    Kenzo  NaN       1      yes
i    dog     Milo  7.0       2       no
j    dog   Cooper  3.0       1       no
k    dog    Buddy  5.5       2    False

In [49]:
# Add 'price' column with value based on animal priority - 10 for non-priority, 20 for priority
animals["price"] = np.where(animals["priority"] == "yes", 20, 10)
animals

  animal     name  age  visits priority  price
a    cat    Daisy  2.5       1      yes     20
b    cat    Bella  3.0       3      yes     20
c  snake   Noodle  0.5       2       no     10
d    dog  Charlie  NaN       3      yes     20
e    dog      Max  5.0       2       no     10
f    cat    Molly  2.0       3       no     10
g  snake    Draco  4.5       1       no     10
h    cat    Kenzo  NaN       1      yes     20
i    dog     Milo  7.0       2       no     10
j    dog   Cooper  3.0       1       no     10
k    dog    Buddy  5.5       2    False     10

In [50]:
animals["total"] = animals["price"] * animals["visits"]
animals

  animal     name  age  visits priority  price  total
a    cat    Daisy  2.5       1      yes     20     20
b    cat    Bella  3.0       3      yes     20     60
c  snake   Noodle  0.5       2       no     10     20
d    dog  Charlie  NaN       3      yes     20     60
e    dog      Max  5.0       2       no     10     20
f    cat    Molly  2.0       3       no     10     30
g  snake    Draco  4.5       1       no     10     10
h    cat    Kenzo  NaN       1      yes     20     20
i    dog     Milo  7.0       2       no     10     20
j    dog   Cooper  3.0       1       no     10     10
k    dog    Buddy  5.5       2    False     10     20

In [51]:
# Delete priority column
animals.drop(columns=["priority"], axis=1, inplace=True)

In [52]:
# Rename column name: animal to species
animals = animals.rename(columns={"animal": "species"})

### Zadanie 4

In [53]:
# Reset index to integers
animals = animals.reset_index(drop=True)
animals

   species     name  age  visits  price  total
0      cat    Daisy  2.5       1     20     20
1      cat    Bella  3.0       3     20     60
2    snake   Noodle  0.5       2     10     20
3      dog  Charlie  NaN       3     20     60
4      dog      Max  5.0       2     10     20
5      cat    Molly  2.0       3     10     30
6    snake    Draco  4.5       1     10     10
7      cat    Kenzo  NaN       1     20     20
8      dog     Milo  7.0       2     10     20
9      dog   Cooper  3.0       1     10     10
10     dog    Buddy  5.5       2     10     20

In [54]:
# Set name column as df index
animals = animals.set_index("name")
animals

        species  age  visits  price  total
name
Daisy       cat  2.5       1     20     20
Bella       cat  3.0       3     20     60
Noodle    snake  0.5       2     10     20
Charlie     dog  NaN       3     20     60
Max         dog  5.0       2     10     20
Molly       cat  2.0       3     10     30
Draco     snake  4.5       1     10     10
Kenzo       cat  NaN       1     20     20
Milo        dog  7.0       2     10     20
Cooper      dog  3.0       1     10     10
Buddy       dog  5.5       2     10     20

In [55]:
# Drop row with "Max"
animals = animals.drop(index="Max")
animals

        species  age  visits  price  total
name
Daisy       cat  2.5       1     20     20
Bella       cat  3.0       3     20     60
Noodle    snake  0.5       2     10     20
Charlie     dog  NaN       3     20     60
Molly       cat  2.0       3     10     30
Draco     snake  4.5       1     10     10
Kenzo       cat  NaN       1     20     20
Milo        dog  7.0       2     10     20
Cooper      dog  3.0       1     10     10
Buddy       dog  5.5       2     10     20

In [56]:
# Reset index to integers, and keep 'name' as column
animals = animals.reset_index()

In [57]:
animals

      name species  age  visits  price  total
0    Daisy     cat  2.5       1     20     20
1    Bella     cat  3.0       3     20     60
2   Noodle   snake  0.5       2     10     20
3  Charlie     dog  NaN       3     20     60
4    Molly     cat  2.0       3     10     30
5    Draco   snake  4.5       1     10     10
6    Kenzo     cat  NaN       1     20     20
7     Milo     dog  7.0       2     10     20
8   Cooper     dog  3.0       1     10     10
9    Buddy     dog  5.5       2     10     20

### Zadanie 5

In [58]:
animals["species"] = animals["species"].apply(str.capitalize)

In [59]:
animals

      name species  age  visits  price  total
0    Daisy     Cat  2.5       1     20     20
1    Bella     Cat  3.0       3     20     60
2   Noodle   Snake  0.5       2     10     20
3  Charlie     Dog  NaN       3     20     60
4    Molly     Cat  2.0       3     10     30
5    Draco   Snake  4.5       1     10     10
6    Kenzo     Cat  NaN       1     20     20
7     Milo     Dog  7.0       2     10     20
8   Cooper     Dog  3.0       1     10     10
9    Buddy     Dog  5.5       2     10     20

In [60]:
# Save dataframe to csv file without indexing
animals.to_csv("animals.csv", index=False)

In [61]:
# Read CSV file
pd.read_csv("animals.csv")

      name species  age  visits  price  total
0    Daisy     Cat  2.5       1     20     20
1    Bella     Cat  3.0       3     20     60
2   Noodle   Snake  0.5       2     10     20
3  Charlie     Dog  NaN       3     20     60
4    Molly     Cat  2.0       3     10     30
5    Draco   Snake  4.5       1     10     10
6    Kenzo     Cat  NaN       1     20     20
7     Milo     Dog  7.0       2     10     20
8   Cooper     Dog  3.0       1     10     10
9    Buddy     Dog  5.5       2     10     20

### Zadanie 6

In [62]:
weather = pd.read_csv("weather.csv")

In [63]:
weather

,Date,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,...,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RISK_MM,RainTomorrow
0,2007-11-01,Canberra,8.0,24.3,0.0,3.4,6.3,NW,30.0,SW,...,29,1019.7,1015.0,7,7,14.4,23.6,No,3.6,Yes
1,2007-11-02,Canberra,14.0,26.9,3.6,4.4,9.7,ENE,39.0,E,...,36,1012.4,1008.4,5,3,17.5,25.7,Yes,3.6,Yes
2,2007-11-03,Canberra,13.7,23.4,3.6,5.8,3.3,NW,85.0,N,...,69,1009.5,1007.2,8,7,15.4,20.2,Yes,39.8,Yes
3,2007-11-04,Canberra,13.3,15.5,39.8,7.2,9.1,NW,54.0,WNW,...,56,1005.5,1007.0,2,7,13.5,14.1,Yes,2.8,Yes
4,2007-11-05,Canberra,7.6,16.1,2.8,5.6,10.6,SSE,50.0,SSE,...,49,1018.3,1018.5,7,7,11.1,15.4,Yes,0.0,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
361,2008-10-27,Canberra,9.0,30.7,0.0,7.6,12.1,NNW,76.0,SSE,...,15,1016.1,1010.8,1,3,20.4,30.0,No,0.0,No
362,2008-10-28,Canberra,7.1,28.4,0.0,11.6,12.7,N,48.0,NNW,...,22,1020.0,1016.9,0,1,17.2,28.2,No,0.0,No
363,2008-10-29,Canberra,12.5,19.9,0.0,8.4,5.3,ESE,43.0,ENE,...,47,1024.0,1022.8,3,2,14.5,18.3,No,0.0,No
364,2008-10-30,Canberra,12.5,26.9,0.0,5.0,7.1,NW,46.0,SSW,...,39,1021.0,1016.2,6,7,15.8,25.9,No,0.0,No
365,2008-10-31,Canberra,12.3,30.2,0.0,6.0,12.6,NW,78.0,NW,...,13,1009.6,1009.2,1,1,23.8,28.6,No,0.0,No

In [64]:
weather = weather.drop(columns=["Location"])

In [65]:
weather["Date"] = pd.to_datetime(weather["Date"])

In [66]:
weather.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 366 entries, 0 to 365
Data columns (total 23 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Date           366 non-null    datetime64[ns]
 1   MinTemp        366 non-null    float64
 2   MaxTemp        366 non-null    float64
 3   Rainfall       366 non-null    float64
 4   Evaporation    366 non-null    float64
 5   Sunshine       363 non-null    float64
 6   WindGustDir    363 non-null    object
 7   WindGustSpeed  364 non-null    float64
 8   WindDir9am     335 non-null    object
 9   WindDir3pm     365 non-null    object
 10  WindSpeed9am   359 non-null    float64
 11  WindSpeed3pm   366 non-null    int64
 12  Humidity9am    366 non-null    int64
 13  Humidity3pm    366 non-null    int64
 14  Pressure9am    366 non-null    float64
 15  Pressure3pm    366 non-null    float64
 16  Cloud9am       366 non-null    int64
 17  Cloud3pm       366 non-null    int64
 18  Temp9am        366 non-null    float64
 19  Temp3pm        366 non-null    float64
 20  RainToday      366 non-null    object
 21  RISK_MM        366 non-null    float64
 22  RainTomorrow   366 non-null    object
dtypes: datetime64[ns](1), float64(12), int64(5), object(5)
memory usage: 65.9+ KB

In [67]:
weather.tail(7)

,Date,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,...,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RISK_MM,RainTomorrow
359,2008-10-25,3.3,25.5,0.0,5.2,10.8,N,43.0,N,NNW,...,16,1018.8,1014.6,0,3,12.0,24.8,No,0.0,No
360,2008-10-26,7.9,26.1,0.0,6.8,3.5,NNW,43.0,NaN,WNW,...,20,1017.6,1014.2,5,8,16.3,25.9,No,0.0,No
361,2008-10-27,9.0,30.7,0.0,7.6,12.1,NNW,76.0,SSE,NW,...,15,1016.1,1010.8,1,3,20.4,30.0,No,0.0,No
362,2008-10-28,7.1,28.4,0.0,11.6,12.7,N,48.0,NNW,NNW,...,22,1020.0,1016.9,0,1,17.2,28.2,No,0.0,No
363,2008-10-29,12.5,19.9,0.0,8.4,5.3,ESE,43.0,ENE,ENE,...,47,1024.0,1022.8,3,2,14.5,18.3,No,0.0,No
364,2008-10-30,12.5,26.9,0.0,5.0,7.1,NW,46.0,SSW,WNW,...,39,1021.0,1016.2,6,7,15.8,25.9,No,0.0,No
365,2008-10-31,12.3,30.2,0.0,6.0,12.6,NW,78.0,NW,WNW,...,13,1009.6,1009.2,1,1,23.8,28.6,No,0.0,No

### Zadanie 7

In [68]:
cols_to_convert = ["RainToday", "RainTomorrow"]

# Use map to convert all "yes" values to True, otherwise insert False
weather[cols_to_convert] = weather[cols_to_convert].map(lambda x: x == "yes")

In [69]:
weather

,Date,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,...,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RISK_MM,RainTomorrow
0,2007-11-01,8.0,24.3,0.0,3.4,6.3,NW,30.0,SW,NW,...,29,1019.7,1015.0,7,7,14.4,23.6,False,3.6,False
1,2007-11-02,14.0,26.9,3.6,4.4,9.7,ENE,39.0,E,W,...,36,1012.4,1008.4,5,3,17.5,25.7,False,3.6,False
2,2007-11-03,13.7,23.4,3.6,5.8,3.3,NW,85.0,N,NNE,...,69,1009.5,1007.2,8,7,15.4,20.2,False,39.8,False
3,2007-11-04,13.3,15.5,39.8,7.2,9.1,NW,54.0,WNW,W,...,56,1005.5,1007.0,2,7,13.5,14.1,False,2.8,False
4,2007-11-05,7.6,16.1,2.8,5.6,10.6,SSE,50.0,SSE,ESE,...,49,1018.3,1018.5,7,7,11.1,15.4,False,0.0,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
361,2008-10-27,9.0,30.7,0.0,7.6,12.1,NNW,76.0,SSE,NW,...,15,1016.1,1010.8,1,3,20.4,30.0,False,0.0,False
362,2008-10-28,7.1,28.4,0.0,11.6,12.7,N,48.0,NNW,NNW,...,22,1020.0,1016.9,0,1,17.2,28.2,False,0.0,False
363,2008-10-29,12.5,19.9,0.0,8.4,5.3,ESE,43.0,ENE,ENE,...,47,1024.0,1022.8,3,2,14.5,18.3,False,0.0,False
364,2008-10-30,12.5,26.9,0.0,5.0,7.1,NW,46.0,SSW,WNW,...,39,1021.0,1016.2,6,7,15.8,25.9,False,0.0,False
365,2008-10-31,12.3,30.2,0.0,6.0,12.6,NW,78.0,NW,WNW,...,13,1009.6,1009.2,1,1,23.8,28.6,False,0.0,False

In [70]:
wind_dir_cols_to_convert = ["WindGustDir", "WindDir9am", "WindDir3pm", ]
weather[wind_dir_cols_to_convert] = weather[wind_dir_cols_to_convert].astype("category")

In [71]:
weather.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 366 entries, 0 to 365
Data columns (total 23 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Date           366 non-null    datetime64[ns]
 1   MinTemp        366 non-null    float64
 2   MaxTemp        366 non-null    float64
 3   Rainfall       366 non-null    float64
 4   Evaporation    366 non-null    float64
 5   Sunshine       363 non-null    float64
 6   WindGustDir    363 non-null    category
 7   WindGustSpeed  364 non-null    float64
 8   WindDir9am     335 non-null    category
 9   WindDir3pm     365 non-null    category
 10  WindSpeed9am   359 non-null    float64
 11  WindSpeed3pm   366 non-null    int64
 12  Humidity9am    366 non-null    int64
 13  Humidity3pm    366 non-null    int64
 14  Pressure9am    366 non-null    float64
 15  Pressure3pm    366 non-null    float64
 16  Cloud9am       366 non-null    int64
 17  Cloud3pm       366 non-null    int64
 18  Temp9am        366 non-null    float64
 19  Temp3pm        366 non-null    float64
 20  RainToday      366 non-null    bool
 21  RISK_MM        366 non-null    float64
 22  RainTomorrow   366 non-null    bool
dtypes: bool(2), category(3), datetime64[ns](1), float64(12), int64(5)
memory usage: 55.4 KB

In [72]:
date_mask = (weather["Date"] > "2008-2-1") & (weather["Date"] <= "2008-2-14")

weather.loc[date_mask]

,Date,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,...,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RISK_MM,RainTomorrow
93,2008-02-02,14.9,28.8,0.0,5.8,8.1,NNE,30.0,SSE,NNE,...,44,1018.2,1014.5,7,2,19.1,27.0,False,0.0,False
94,2008-02-03,17.1,29.6,0.0,5.8,9.2,E,48.0,SE,ESE,...,38,1016.7,1012.8,6,7,21.7,29.1,False,1.8,False
95,2008-02-04,18.2,22.6,1.8,8.0,0.0,ENE,33.0,SSE,ENE,...,76,1014.4,1011.5,8,8,18.5,22.1,False,9.0,False
96,2008-02-05,16.8,22.8,9.0,2.8,0.3,ESE,30.0,S,SSE,...,71,1010.0,1007.8,8,8,18.4,21.5,False,1.0,False
97,2008-02-06,13.6,27.4,1.0,2.8,8.0,W,52.0,NW,WNW,...,41,1002.1,997.5,4,7,18.7,26.5,False,0.0,False
98,2008-02-07,14.5,24.2,0.0,6.8,5.9,SSW,61.0,N,NNW,...,76,999.4,998.9,7,7,17.9,20.3,False,16.2,False
99,2008-02-08,12.4,19.9,16.2,5.4,5.6,ENE,41.0,ESE,ESE,...,58,1007.6,1005.0,7,7,13.6,18.7,False,0.0,False
100,2008-02-09,10.4,20.9,0.0,4.0,8.9,SSE,33.0,S,S,...,51,1007.7,1006.8,6,6,13.8,18.7,False,0.0,False
101,2008-02-10,9.1,23.1,0.0,5.8,9.6,ENE,41.0,SSE,W,...,37,1013.6,1011.4,1,7,14.0,21.4,False,0.0,False
102,2008-02-11,8.9,26.0,0.0,5.0,10.7,NE,31.0,SE,NE,...,34,1016.1,1011.7,1,5,14.6,24.2,False,4.4,False
103,2008-02-12,14.5,24.2,4.4,6.6,5.9,W,48.0,NNW,WNW,...,60,1010.8,1006.8,8,5,15.8,22.6,False,11.0,False
104,2008-02-13,12.6,18.2,11.0,3.2,0.4,ENE,30.0,SSE,SSE,...,73,1010.0,1011.0,7,8,16.3,16.8,False,0.2,False
105,2008-02-14,8.6,24.2,0.2,2.8,12.7,E,33.0,S,SE,...,37,1017.5,1015.1,1,1,13.7,22.0,False,0.0,False

In [73]:
wind_mask = (weather["WindDir9am"] == "SSW") | (weather["WindDir9am"] == "SW")

weather.loc[wind_mask]

,Date,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,...,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RISK_MM,RainTomorrow
0,2007-11-01,8.0,24.3,0.0,3.4,6.3,NW,30.0,SW,NW,...,29,1019.7,1015.0,7,7,14.4,23.6,False,3.6,False
17,2007-11-18,11.7,30.0,1.2,7.2,10.1,S,52.0,SW,NE,...,26,1016.4,1013.0,1,5,20.1,28.6,False,0.6,False
29,2007-11-30,13.6,24.1,0.4,2.6,0.5,NNW,30.0,SSW,S,...,49,1017.2,1013.3,8,7,17.3,23.2,False,22.6,False
59,2007-12-30,15.4,35.0,0.0,9.6,13.0,E,39.0,SSW,ESE,...,18,1017.4,1015.0,1,1,23.4,34.3,False,0.0,False
153,2008-04-02,5.3,23.3,0.0,3.6,5.6,NNW,83.0,SSW,NW,...,26,1018.0,1010.5,1,8,9.5,22.5,False,2.6,False
157,2008-04-06,5.9,21.8,0.0,2.8,9.3,E,35.0,SSW,NNW,...,35,1028.0,1024.1,1,5,12.9,20.8,False,0.0,False
163,2008-04-12,6.1,24.1,0.0,4.6,6.1,WNW,35.0,SSW,WNW,...,32,1019.2,1015.8,7,3,11.5,23.7,False,2.0,False
168,2008-04-17,5.3,21.0,0.0,4.6,6.3,WNW,26.0,SSW,NW,...,44,1027.2,1023.3,7,2,12.0,20.4,False,0.0,False
183,2008-05-02,2.1,17.3,0.0,1.6,9.2,W,43.0,SSW,WNW,...,38,1020.0,1017.3,1,2,8.7,15.9,False,0.0,False
185,2008-05-04,-0.9,16.7,0.0,2.4,9.3,NNW,30.0,SW,NNW,...,42,1022.7,1018.5,5,2,6.2,15.4,False,0.0,False
228,2008-06-16,6.4,16.9,0.0,2.6,5.9,SSW,26.0,SSW,ESE,...,51,1027.8,1024.8,7,2,9.5,16.0,False,0.0,False
229,2008-06-17,5.4,15.5,0.0,1.6,5.8,NNE,20.0,SSW,NNE,...,58,1028.6,1025.5,7,1,9.4,14.9,False,0.0,False
246,2008-07-04,-3.1,12.0,0.0,1.8,3.9,ESE,35.0,SSW,NE,...,52,1030.5,1030.0,1,6,5.9,10.2,False,0.0,False
256,2008-07-14,2.7,16.5,0.0,0.6,8.9,NNW,41.0,SW,NNW,...,51,1021.8,1019.0,5,1,6.7,15.9,False,0.0,False
270,2008-07-28,-1.6,10.7,1.4,0.8,9.1,S,59.0,SSW,S,...,56,1014.1,1014.9,2,4,5.6,9.6,False,0.0,False
296,2008-08-23,2.3,11.6,0.0,5.4,9.5,S,54.0,SSW,ESE,...,38,1025.9,1025.5,1,1,6.7,11.1,False,0.0,False
298,2008-08-25,-0.9,14.2,0.0,2.6,7.8,WNW,31.0,SSW,N,...,34,1030.2,1024.4,7,6,5.3,12.8,False,0.0,False
303,2008-08-30,0.5,16.3,0.0,1.8,4.1,NNW,39.0,SSW,WSW,...,45,1023.7,1017.5,7,8,6.2,15.4,False,4.0,False
314,2008-09-10,-2.7,15.2,0.0,4.0,9.7,N,30.0,SW,WNW,...,35,1022.8,1017.9,1,2,6.3,14.9,False,0.0,False
321,2008-09-17,0.7,14.1,0.0,5.6,9.0,ENE,20.0,SSW,NNW,...,43,1026.7,1022.1,7,1,7.4,13.7,False,0.0,False
335,2008-10-01,1.4,20.6,0.0,5.4,11.1,N,46.0,SW,N,...,16,1020.8,1015.4,5,1,11.3,19.5,False,0.0,False
345,2008-10-11,8.2,22.4,0.0,5.4,11.2,NW,31.0,SSW,NW,...,30,1027.8,1023.8,1,3,13.6,20.6,False,0.0,False
350,2008-10-16,4.4,21.0,0.0,4.2,12.2,NW,28.0,SW,NW,...,30,1025.7,1022.3,1,1,9.6,19.2,False,0.0,False
364,2008-10-30,12.5,26.9,0.0,5.0,7.1,NW,46.0,SSW,WNW,...,39,1021.0,1016.2,6,7,15.8,25.9,False,0.0,False

### Zadanie 8

In [74]:
emp_det = pd.read_excel("employee.xlsx", sheet_name="employee_details")
emp_perf = pd.read_excel("employee.xlsx", sheet_name="performance")

In [75]:
emp_perf.set_index("name", drop=True)
emp_det.set_index("name", drop=True)

                age   income gender  department grade
name
Allen Smith    45.0      NaN    NaN  Operations    G3
S Kumar         NaN  16000.0      F     Finance    G0
Jack Morgan    32.0  35000.0      M     Finance    G2
Ying Chin      45.0  65000.0      F       Sales    G3
Dheeraj Patel  30.0  42000.0      F  Operations    G2
Satyam Sharma   NaN  62000.0    NaN       Sales    G3
James Authur   54.0      NaN      F  Operations    G3
Josh Wills     54.0  52000.0      F     Finance    G3
Leo Duck       23.0  98000.0      M       Sales    G4

In [76]:
employees = emp_det.merge(emp_perf)

In [77]:
employees

            name   age   income gender  department grade  performance_score
0    Allen Smith  45.0      NaN    NaN  Operations    G3                723
1        S Kumar   NaN  16000.0      F     Finance    G0                520
2    Jack Morgan  32.0  35000.0      M     Finance    G2                674
3      Ying Chin  45.0  65000.0      F       Sales    G3                556
4  Dheeraj Patel  30.0  42000.0      F  Operations    G2                711
5  Satyam Sharma   NaN  62000.0    NaN       Sales    G3                649
6   James Authur  54.0      NaN      F  Operations    G3                 53
7     Josh Wills  54.0  52000.0      F     Finance    G3                901
8       Leo Duck  23.0  98000.0      M       Sales    G4                709

In [78]:
employees.columns = employees.columns.str.capitalize()

In [79]:
employees.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Name               9 non-null      object
 1   Age                7 non-null      float64
 2   Income             7 non-null      float64
 3   Gender             7 non-null      object
 4   Department         9 non-null      object
 5   Grade              9 non-null      object
 6   Performance_score  9 non-null      int64
dtypes: float64(2), int64(1), object(4)
memory usage: 636.0+ bytes

### Zadanie 9

In [80]:
finance_mask = (employees["Department"] == "Finance") & (employees["Income"] > 20000)

emp_finance = employees.loc[finance_mask]
emp_finance

          Name   Age   Income Gender Department Grade  Performance_score
2  Jack Morgan  32.0  35000.0      M    Finance    G2                674
7   Josh Wills  54.0  52000.0      F    Finance    G3                901

In [81]:
emp_finance.to_excel("emp_finance.xlsx", "employee_finance")

/tmp/ipykernel_13883/118485278.py:1: FutureWarning: Starting with pandas version 3.0 all arguments of to_excel except for the argument 'excel_writer' will be keyword-only.
  emp_finance.to_excel("emp_finance.xlsx", "employee_finance")